### DISCUSSION TITLE
Warp Nord port

### DISCUSSION THREAD

**Discussion by arrrni** [arcticicestudio/nord#236] [Suggestions & Ideas]
Hello!
I've created a port of Nord theme for [Warp](https://www.warp.dev/) terminal based on iTerm2 port. Here's the code:
```
accent: "#5E81AC"
foreground: "#d8dde8"
terminal_colors:
  normal:
    magenta: "#b48dac"
    white: "#e5e8ef"
    cyan: "#88bfcf"
    black: "#3b4151"
    green: "#a3bd8b"
    red: "#be6069"
    blue: "#81a0c0"
    yellow: "#ebca8a"
  bright:
    green: "#a3bd8b"
    red: "#be6069"
    white: "#eceef3"
    black: "#4c5569"
    blue: "#81a0c0"
    cyan: "#8fbbba"
    magenta: "#b48dac"
    yellow: "#ebca8a"
details: "darker"
background: "#2e333f"
```
Just place it into `~/.warp/themes/` in a file named `nord.yaml` and enjoy!
