### ISSUE TITLE
Unable to use in SCSS

### ISSUE THREAD

**Issue by Android789515** [arcticicestudio/nord#260]
The provided method for importing the color theme is:

```scss
@import "node_modules/nord/src/nord.scss";

body {
  background-color: $nord0;
  color: $nord8;
}

```

First of all, the path is incorrect, the file is actually located in `node_modules/nord/src/sass/nord.scss`.

When I fix the path I still can't use the variables provided.
